---
title: "R Notebook"
editor_options: 
  chunk_output_type: console
---


```{r libs}
# library(MASS)
# library(matrixcalc)
# library(Matrix)
library(tidyr)
library(ggplot2)

# library(fabletools)
# library(fable)
# library(feasts)
library(tsibble)
library(dplyr)

library(devtools)
load_all()

library(purrr)
```


# Read

```{r}
file <- "S4-2-1_100"
path <- paste("sim_results/", file, ".rds", sep = "")
results <- readRDS(path)

MSE <- results$MSE
W_shr <- results$W_shr
W_n <- results$W_n
```

# Inspect

```{r}
transfrom_sim_MSE <- function(MSE, to_ts = T) {
  df <- imap_dfr(MSE, function(mat, model_name) {
    as_tibble(mat) %>%
      mutate(h = row_number()) %>%
      pivot_longer(cols = -h, names_to = "series", values_to = "MSE") %>%
      mutate(
        .model = model_name,
      ) %>%
      select(.model, series, h, MSE)
  })
  if (to_ts) {
    return(
      as_tsibble(key = c(.model, series), index = h)
    )
  }
  return(df)
}

MSE_ts <- transfrom_sim_MSE(results$MSE, F)

MSE_ts |> group_by(.model, h) |>
  summarise(mse = mean(MSE)) |>
  ggplot(aes(x = h, y = mse, color = .model)) +
    geom_line() +
    labs(x = "Horizon", y = "MSE") +
    theme_minimal()

MSE_ts |>
  group_by(series, h) |>
  mutate(
    base_MSE = MSE[.model == "base"]
  ) |>
  ungroup() |>
  group_by(.model, h) |>
  summarise(
    MSE = mean(MSE),
    base_MSE = mean(base_MSE),
    pct_change = (MSE - base_MSE) / base_MSE * 100
  ) |>
  filter(h <=16) |>
  ggplot(aes(x = h, y = pct_change, color = .model)) +
    geom_line() +
    labs(x = "Horizon", y = "% relative improvements in MSE") +
    theme_minimal()
```

```{r}
# params from shrinkage and novelist
results <- sim2

plot(
  results$W_shr,
  results$W_n[,1]
)

# filter diff
cond <- results$W_shr != results$W_n[,1]
# cond <- results$W_shr != results$W_n[,1] & results$W_n[,1] < 0.3

sum(!cond)/length(results$W_shr) # proportion of similarity in lambda

# lambdas given thresholded != identity
plot(
  results$W_shr[cond],
  results$W_n[,1][cond]
); abline(a = 0, b = 1, col = "red", lty = 1)

# lambda vs delta NOVELIST
plot(results$W_n)
# given thresholded != identity
plot(
  results$W_n[,1][cond],
  results$W_n[,2][cond]
)

hist(results$W_n[,2])
hist(results$W_n[,2][cond])
```

# NOVELIST where not collapse to identity

```{r}
errors[1]
```


# Compare between 2 simulations

```{r}
MSE1 <- transfrom_sim_MSE(sim1$MSE, F)
MSE2 <- transfrom_sim_MSE(sim2$MSE, F)

hier_level <- MSE1$series |>
  substring(1, 1) |>
  unique() |> sort(decreasing = TRUE)

MSE_full <- bind_rows(MSE1, MSE2, .id = "id") |>
  mutate(
    level = match(substring(series,1,1), hier_level) 
  )

# plot by h
MSE_full |> group_by(id, .model, h) |>
  summarise(mse = mean(MSE)) |>
  filter(h <=16) |>
  ggplot(aes(x = h, y = mse, color = .model)) +
    geom_line() +
    facet_wrap(~id) +
    labs(x = "Horizon", y = "MSE") +
    theme_minimal()

# plot by h and hier-level
MSE_full |> 
  group_by(id, .model, h, level) |>
  summarise(mse = mean(MSE)) |>
  filter(h <= 10) |>
  mutate(facet_id = paste0(id, level)) |>
  ggplot(aes(x = h, y = mse, color = .model)) +
    geom_line() +
    facet_wrap(~ facet_id, nrow=2, scales = "free_y") +
    labs(x = "Horizon", y = "MSE") +
    theme_minimal()
# plot by h and hier-level
  
```


```{r}
# pct change

MSE_full |>
  group_by(id, series, h) |>
  mutate(
    base_MSE = MSE[.model == "base"]
  ) |>
  ungroup() |>
  group_by(id, .model, h) |>
  summarise(
    MSE = mean(MSE),
    base_MSE = mean(base_MSE),
    pct_change = (MSE - base_MSE) / base_MSE * 100
  ) |>
  mutate(id = ifelse(id == 1, "T = 100", "T = 300")) |>
  filter(h <=16) |>
  ggplot(aes(x = h, y = pct_change, color = .model)) +
    geom_line() +
    facet_wrap(~id) +
    labs(x = "Horizon", y = "% relative improvements in MSE") +
    theme_minimal()
```


