// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// novelist_est_cpp
Rcpp::List novelist_est_cpp(const arma::mat& resid, double delta, Rcpp::Nullable<double> lambda_in, bool zero_mean);
RcppExport SEXP _ReconCov_novelist_est_cpp(SEXP residSEXP, SEXP deltaSEXP, SEXP lambda_inSEXP, SEXP zero_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type resid(residSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type lambda_in(lambda_inSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_mean(zero_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(novelist_est_cpp(resid, delta, lambda_in, zero_mean));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ReconCov_novelist_est_cpp", (DL_FUNC) &_ReconCov_novelist_est_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ReconCov(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
