# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title NOVELIST covariance estimator, Rcpp version
#'
#' @seealso \code{\link[=novelist_est]}
#' @useDynLib ReconCov
#' @import Rcpp
#' @importFrom Rcpp sourceCpp
#' @import RcppArmadillo
#' @export
novelist_est_cpp <- function(resid, delta, lambda_in = NULL, zero_mean = TRUE) {
    .Call('_ReconCov_novelist_est_cpp', PACKAGE = 'ReconCov', resid, delta, lambda_in, zero_mean)
}

#' Outsource the two for loops in novelist_cv into C++
#'
novelist_cov_grid_cpp <- function(resid, deltas, window_size, zero_mean = TRUE) {
    .Call('_ReconCov_novelist_cov_grid_cpp', PACKAGE = 'ReconCov', resid, deltas, window_size, zero_mean)
}

